name: flashcard_quiz_app
description: A simple Flashcard Quiz App for CodeAlpha Internship
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
